# Generated by Django 3.2.1 on 2021-05-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('speaker', models.CharField(choices=[('Attendee', 'Attendee'), ('Speaker', 'Speaker')], default='Attendee', max_length=150)),
                ('topic', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.participants')),
            ],
        ),
    ]
